s3_bucket_name = "jr-source-video-bucket"
sns_topic_name = "zoom-recording-alerts"
lambda_runtime = "python3.11"                                                                                       # remember to update this if you change the runtime
sns_email = "captainboris246281@gmail.com"
zoom_webhook_secret_token = "123456789"
mongodb_api_endpoint = "https://api.zoom.us/v2/meetings/123456789/recordings"
lambda_s3_bucket = "jr-lambda-zip-bucket"                                                                            # remember to create one before provisioning
lambda_zip_path = "lambda_function_V01.zip"
aws_lambda_layer_version_arn = "arn:aws:lambda:ap-southeast-2:417805623903:layer:python-requests-layer-11-86-1113:1" # remember to create one before provisioning
