s3_bucket_name = "jr-source-video-bucket"
sns_topic_name = "zoom-recording-alerts"
lambda_runtime = "python3.8"
lambda_zip_path = "../lambda_code/lambda_function.zip"
sns_email = "gxbyunyun@gmail.com"
